version: '3'
services:
  website:
    build: .
    env_file: .env
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
    links:
      - mongodb

  mongodb:
    image: mongo
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
        - '27017:27017'
    command: mongod --smallfiles --logpath=/dev/null # --quiet
